- name: Download the backup file from master (on slaves)
  fetch:
    src: "{{ latest_backup_file.stdout }}"
    dest: "{{ backup_directory }}"
    flat: yes
  when: inventory_hostname == master_host

- name: Import the backup file to slave
  shell: |
    mysql -u root -p'{{ replication_password }}' < "{{ backup_directory }}/{{ latest_backup_file.stdout | basename }}"
  when: inventory_hostname == master_host
